version: '2'
services:
    carotsaver-app:
        image: carotsaver
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://carotsaver-mysql:3306/carotsaver?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    carotsaver-mysql:
        extends:
            file: mysql.yml
            service: carotsaver-mysql
